#!/usr/bin/env bash

# atomicity - if single line fails, entire script should exit
set -e

# traps program exit and deletes deploy branch at exit
function cleanup_at_exit {
    git checkout master
    git branch -D deploy
}

git checkout -b deploy

# webpack in production mode
webpack -p

# force add gitignored build files
git add -f public/bundle.js public/bundle.js.map

git commit --allow-empty -m 'Deploying'

git push --force heroku deploy:master
